[package]
name = "pk_parser"
version = "0.0.2-dev.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pk_lexer = { version = "0.0.2-dev", path = "../lexer" }
